server:
  port: 8083
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:derby:memory:local;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    show-sql: true
