spring:
  application:
    name: config-service
  profiles:
    active: native
  security:
    user:
      name: root
      password: s3cr3t
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888
